import assert from "node:assert/strict";
import { build } from "esbuild";
async function load(entry) {
  const result = await build({ entryPoints: [entry], bundle: true, write: false, platform: "node", format: "esm", plugins: [{ name: "isolated-supabase", setup(builder) {
    builder.onResolve({ filter: /^@\/lib\/supabase$/ }, () => ({ path: "mock", namespace: "test" }));
    builder.onLoad({ filter: /.*/, namespace: "test" }, () => ({ contents: 'export const BUCKET = "novels"; export function supabase() { return globalThis.testApi; }' }));
  } }] });
  return import(`data:text/javascript;base64,${Buffer.from(result.outputFiles[0].text).toString("base64")}`);
}
const { sortBooks, sortVolumes } = await load("src/lib/reader-navigation.ts");
const base = { created_at: "2026-01-01", volume_id: null, sort_order: 0, chapter_title: null, title: "Chapter" };
const books = [12.5, 0, 2, 1].map((n) => ({ ...base, id: String(n), chapter_number: n }));
assert.deepEqual(sortBooks(books, []).map((b) => b.chapter_number), [0, 1, 2, 12.5]);
assert.equal(books[0].chapter_number, 12.5);
assert.deepEqual(sortVolumes([2, 0, 1].map(n => ({ id: String(n), sort_order: 0, volume_number: n, created_at: base.created_at }))).map(v => v.volume_number), [0, 1, 2]);
const { extractReadingBlocks } = await load("src/lib/reader-text.ts");
const item = (str, y) => ({ str, hasEOL: true, transform: [12,0,0,12,30,y], height: 12, width: 100 });
const blocks = extractReadingBlocks([item("Chapter 1", 760), item("An extraordinary journey", 720), item("continued across the valley.", 700), item("Page 1", 30)], [0,0,600,800]);
assert.equal(blocks[0].kind, "heading");
assert.match(blocks[1].text, /journey continued/);
assert.ok(blocks.every(b => !b.text.includes("Page 1") && b.position >= 0 && b.position <= 1));
assert.deepEqual(extractReadingBlocks([null, { foo: 1 }], [0,0,600,800]), []);
const urls = await load("src/lib/private-media-url.ts");
globalThis.testApi = { storage: { from: () => ({ createSignedUrl: async (_, ttl) => ({ data: { signedUrl: `https://example.invalid/media?ttl=${ttl}` }, error: null }) }) } };
const before = Date.now();
const signed = await urls.createPrivateMediaUrl("novels", "test.pdf", 60);
assert.ok(signed.expiresAt >= before + 60000 && signed.expiresAt <= Date.now() + 60000);
assert.equal(urls.isPrivateMediaAuthorizationError({ status: 403 }), true);
assert.equal(urls.isPrivateMediaAuthorizationError({ status: 500 }), false);
globalThis.testApi.storage.from = () => ({ createSignedUrl: async () => ({ data: null, error: { status: 403 } }) });
await assert.rejects(urls.createPrivateMediaUrl("novels", "test.pdf"));
const { saveReadingProgress } = await load("src/lib/data/progress.ts");
const writes = [], releases = [];
globalThis.testApi = { from: () => ({ upsert: (row) => { writes.push(row.page_number); return new Promise(resolve => releases.push(resolve)); } }) };
const first = saveReadingProgress("a", "book", { page_number: 1 });
const second = saveReadingProgress("a", "book", { page_number: 2 });
await new Promise(setImmediate);
assert.deepEqual(writes, [1]);
releases.shift()({ data: null, error: null });
await first;
await new Promise(setImmediate);
assert.deepEqual(writes, [1, 2]);
releases.shift()({ data: null, error: null });
await second;
const failed = saveReadingProgress("a", "book", { page_number: 3 });
const rejected = assert.rejects(failed);
const recovery = saveReadingProgress("a", "book", { page_number: 4 });
await new Promise(setImmediate);
releases.shift()({ data: null, error: { message: "network" } });
await rejected;
await new Promise(setImmediate);
releases.shift()({ data: null, error: null });
await recovery;
assert.deepEqual(writes, [1,2,3,4]);
delete globalThis.testApi;
console.log("PASS: navigation ordering, PDF text, private URL expiry/revocation and serialized progress recovery.");
